title: <p align="center"> Nareshkumar </p>

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nareshkumar-g-86230a238/">LinkedIn</a> |
  <a href="https://github.com/Nareshkumar2112">GitHub</a>
 
  <br>  
  I'm working on developing softwares.
  <br>
  </p>



theme: jekyll-theme-minimal
